[build-system]
requires = ["scikit-build-core>=0.9", "pybind11", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "sgtlearn"
version = "v0.1.0a5"
description = "Shape Generalized Trees learning library"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [{ name = "Nakul Upadhya", email = "nakulupadhya1@gmail.com" },{ name = "Joshua Lee", email = "joshua.lee.9880@gmail.com" },{ name = "Eldan Cohen", email = "eldan.cohen@utoronto.ca" }]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "numpy>=1.20",
  "scikit-learn>=1.3",
  "joblib>=1.2",
  "matplotlib>=3.10.9",
  "seaborn>=0.13.2",
  "graphviz>=0.21",
]

[project.optional-dependencies]
dev = ["pytest>=7", "pybind11-stubgen", "ruff", "black", "mypy"]


[tool.scikit-build]
cmake.source-dir = "cpp"
cmake.version = ">=3.18"
cmake.build-type = "Release"
cmake.args = ["-DSGTLEARN_BUILD_TESTS=OFF"]
wheel.packages = ["sgtlearn"]


[tool.pytest.ini_options]
testpaths = ["tests"]

[[tool.mypy.overrides]]
module = [
  "sklearn",
  "sklearn.*",
  "ShapeGeneralizedTrees",
  "ShapeGeneralizedTrees.*",
  "joblib",
  "joblib.*",
  "numpy",
  "numpy.*",
]
ignore_missing_imports = true

